name: flavor_finder
description: A Flutter food delivery app with ordering workflow

publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  animations: ^2.0.8
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0
  # Real-time & Networking
  socket_io_client: ^2.0.3+1
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  # Search & Voice
  speech_to_text: ^6.3.0
  flutter_typeahead: ^4.8.0
  # Notifications
  flutter_local_notifications: ^16.1.0
  # Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Authentication
  local_auth: ^2.1.6
  # UI Enhancements
  rive: ^0.11.4
  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  # Internationalization
  flutter_localizations:
    sdk: flutter
  # Social Features
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
