name: flavor_finder
description: A Flutter food delivery app with ordering workflow

publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  animations: ^2.0.8
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/